name: Pull & Publish students html submissions

on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/5 * * * *'

permissions:
  id-token: write
  contents: write

jobs:
  pull-latest-code:
    name: Pull latest code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Install github classroom extension
        env:
          GH_TOKEN: ${{ secrets.token }}
        run: |
          gh extension install github/gh-classroom
      - name: Pull students latest code
        env:
          ASSIGNMENT_NAME: my-cart
          ASSIGNMENT_ID: 622206
          GH_TOKEN: ${{ secrets.token }}
        working-directory: ./
        run: scripts/pull-students-latest-code.sh

  upload-latest-code:
    name: Upload latest code
    runs-on: ubuntu-latest
    needs: pull-latest-code
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          name: html-submissions
          path: submissions

  publish-latest-code:
    name: Publish latest code
    runs-on: ubuntu-latest
    needs: upload-latest-code
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Download message artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: html-submissions
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          ACTIONS_STEP_DEBUG: true
          GH_TOKEN: ${{ secrets.token }}
        with:
          artifact_name: html-submissions
